name: Daily Selenium Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    # Daily run at 9:00 AM IST
    - cron: "30 3 * * *"

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Selenium Tests
        run: mvn test